server:
  port: 8080

pki-config:
  dll-name: libph_sdf.so
  pki-key-lable: 14
  pki-key-passwd: 1234567a
  pki-key-algo: 131328
  pki-hash-algo: 1
system:
 cert: MIICDjCCAbWgAwIBAgIIICEDJwAAARcwCgYIKoEcz1UBg3UwPjE8MDoGA1UECgwz5Lit5Y2O5Lq65rCR5YWx5ZKM5Zu95Zu95a625bel5ZWG6KGM5pS/566h55CG5oC75bGAMB4XDTIxMDMyNzAyMzkyMloXDTMxMDMyNzAyMzkyMlowfjELMAkGA1UEBgwCQ04xDzANBgNVBAcMBuWMl+S6rDEhMB8GA1UECgwY5biC5Zy655uR552j566h55CG5oC75bGAMRUwEwYDVQQLDAzkv6Hmga/kuK3lv4MxJDAiBgNVBAMMG+aVsOaNruS4reW/g+aOpeWPo+acjeWKoeWZqDBZMBMGByqGSM49AgEGCCqBHM9VAYItA0IABMb+1QCPG8J+9mCpGdfEqk3j0dncegHnvzeHBOHB7mmStufyWMTLwjS5BXIZiSmrJdmJxd2de1OfYBVLQwsSQ8OjXTBbMAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQDAgEGMB8GA1UdIwQYMBaAFMiKA/q3R18Z+K3x4pBflgP5TTe9MB0GA1UdDgQWBBRCrES8sOXBJIh51jUl3NQCNHEmVDAKBggqgRzPVQGDdQNHADBEAiBREqs8gNZ/JX5xFnEVU0kqjPRrmA/5QxZEeigDWhfZkwIgbuNbJBEbeaVNnT8Ri/8pyZ9p8H2lyXnPjnN1rcVfuW8=